import { describe, expect, it } from 'vitest';

import { buildAdif, parseAdif } from './adif.js';

describe('parseAdif', () => {
  it('parses a simple record with header', () => {
    const text =
      'Generated by SomeLogger\n' +
      '<adif_ver:5>3.1.4 <programid:10>SomeLogger\n' +
      '<eoh>\n' +
      '<call:6>OZ1ABC <qso_date:8>20260815 <time_on:6>142530 <band:3>20m ' +
      '<mode:3>SSB <freq:6>14.250 <rst_sent:2>59 <rst_rcvd:2>57 <eor>\n';

    const { header, qsos } = parseAdif(text);
    expect(header.adif_ver).toBe('3.1.4');
    expect(header.programid).toBe('SomeLogger');
    expect(qsos).toHaveLength(1);
    const q = qsos[0];
    expect(q.call).toBe('OZ1ABC');
    expect(q.qso_date).toBe('20260815');
    expect(q.time_on).toBe('142530');
    expect(q.band).toBe('20m');
    expect(q.mode).toBe('SSB');
    expect(q.freq).toBe(14.25);
    expect(q.rst_sent).toBe('59');
    expect(q.rst_rcvd).toBe('57');
  });

  it('handles mixed/lower-case tags and <EOH>/<EOR> in any case', () => {
    const text = '<ADIF_VER:5>3.1.0<EoH><CaLl:4>W1AW<MODE:2>CW<eOr><call:5>K1ABC<mode:3>FT8<EOR>';
    const { header, qsos } = parseAdif(text);
    expect(header.adif_ver).toBe('3.1.0');
    expect(qsos).toHaveLength(2);
    expect(qsos[0].call).toBe('W1AW');
    expect(qsos[0].mode).toBe('CW');
    expect(qsos[1].call).toBe('K1ABC');
  });

  it('handles the optional :type suffix on fields', () => {
    const { qsos } = parseAdif('<call:5:S>DL1XX <freq:5:N>7.030 <eor>');
    expect(qsos[0].call).toBe('DL1XX');
    expect(qsos[0].freq).toBe(7.03);
  });

  it('trusts the declared length when the visible value is longer', () => {
    // len 4 but 6 chars before the next tag — the extra 2 are garbage
    const { qsos } = parseAdif('<call:4>W1AWXY<mode:2>CW<eor>');
    expect(qsos[0].call).toBe('W1AW');
    expect(qsos[0].mode).toBe('CW');
  });

  it('trusts the declared length when it spans whitespace/newlines (multi-line values)', () => {
    const { qsos } = parseAdif('<call:4>W1AW<comment:11>line1\nline2<eor>');
    expect(qsos[0].comment).toBe('line1\nline2');
  });

  it('clamps a declared length that runs past end-of-text', () => {
    const { qsos } = parseAdif('<call:4>W1AW<eor><comment:500>short');
    expect(qsos).toHaveLength(1);
    expect(qsos[0].call).toBe('W1AW');
  });

  it('routes unknown fields into extras with uppercase names', () => {
    const { qsos } = parseAdif('<call:4>W1AW<My_Antenna:6>dipole<CONTEST_ID:4>CQWW<eor>');
    expect(qsos[0].extras).toEqual({ MY_ANTENNA: 'dipole', CONTEST_ID: 'CQWW' });
  });

  it('tolerates garbage between records', () => {
    const text = '<eoh> junk here\n<call:4>W1AW<eor>\n-- random line --\n<call:5>K1ABC<eor>trailing junk';
    const { qsos } = parseAdif(text);
    expect(qsos.map((q) => q.call)).toEqual(['W1AW', 'K1ABC']);
  });

  it('parses a header-less file (records only)', () => {
    const { header, qsos } = parseAdif('<call:4>W1AW<band:3>40m<eor>');
    expect(header).toEqual({});
    expect(qsos).toHaveLength(1);
    expect(qsos[0].band).toBe('40m');
  });

  it('returns empty results for an empty or null file', () => {
    expect(parseAdif('')).toEqual({ header: {}, qsos: [] });
    expect(parseAdif(null)).toEqual({ header: {}, qsos: [] });
    expect(parseAdif('   \n\n  ')).toEqual({ header: {}, qsos: [] });
  });

  it('uppercases callsigns and keeps unparsable freq in extras', () => {
    const { qsos } = parseAdif('<call:6>oz1abc<freq:3>abc<eor>');
    expect(qsos[0].call).toBe('OZ1ABC');
    expect(qsos[0].freq).toBeUndefined();
    expect(qsos[0].extras.FREQ).toBe('abc');
  });

  it('keeps a trailing record without <eor> only when it has a call', () => {
    const withCall = parseAdif('<call:4>W1AW<mode:2>CW');
    expect(withCall.qsos).toHaveLength(1);
    const junkOnly = parseAdif('<eoh><notes:4>junk');
    expect(junkOnly.qsos).toHaveLength(0);
  });
});

describe('buildAdif', () => {
  const sample = [
    {
      id: 'x1',
      call: 'OZ1ABC',
      qso_date: '20260815',
      time_on: '142530',
      band: '20m',
      mode: 'SSB',
      freq: 14.25,
      rst_sent: '59',
      rst_rcvd: '57',
      gridsquare: 'JO65',
      name: 'Lars',
      comment: 'POTA DK-0001',
      tx_pwr: '100',
      my_gridsquare: 'EM48',
      extras: { CONTEST_ID: 'CQWW' },
    },
  ];

  it('emits a valid header with program identity', () => {
    const text = buildAdif([]);
    expect(text).toMatch(/<adif_ver:5>3\.1\.4/);
    expect(text).toMatch(/<programid:12>OpenHamClock/);
    expect(text).toMatch(/<programversion:\d+>/);
    expect(text).toMatch(/<created_timestamp:15>\d{8} \d{6}/);
    expect(text.toLowerCase()).toContain('<eoh>');
  });

  it('writes model fields, extras, and station_callsign from myCall', () => {
    const text = buildAdif(sample, { myCall: 'k0cjh' });
    expect(text).toContain('<call:6>OZ1ABC');
    expect(text).toContain('<freq:5>14.25');
    expect(text).toContain('<CONTEST_ID:4>CQWW');
    expect(text).toContain('<STATION_CALLSIGN:5>K0CJH');
    expect(text).toMatch(/<eor>/);
  });

  it('omits empty fields and does not duplicate an existing STATION_CALLSIGN', () => {
    const text = buildAdif([{ call: 'W1AW', extras: { STATION_CALLSIGN: 'AA1AA' } }], { myCall: 'K0CJH' });
    expect(text).toContain('<STATION_CALLSIGN:5>AA1AA');
    expect(text).not.toContain('K0CJH');
    expect(text).not.toContain('<band');
    expect(text).not.toContain('<freq');
  });

  it('round-trips losslessly through parseAdif, extras included', () => {
    const text = buildAdif(sample, { myCall: 'K0CJH' });
    const { qsos } = parseAdif(text);
    expect(qsos).toHaveLength(1);
    const q = qsos[0];
    expect(q.call).toBe('OZ1ABC');
    expect(q.qso_date).toBe('20260815');
    expect(q.time_on).toBe('142530');
    expect(q.band).toBe('20m');
    expect(q.mode).toBe('SSB');
    expect(q.freq).toBe(14.25);
    expect(q.rst_sent).toBe('59');
    expect(q.rst_rcvd).toBe('57');
    expect(q.gridsquare).toBe('JO65');
    expect(q.name).toBe('Lars');
    expect(q.comment).toBe('POTA DK-0001');
    expect(q.tx_pwr).toBe('100');
    expect(q.my_gridsquare).toBe('EM48');
    expect(q.extras.CONTEST_ID).toBe('CQWW');
    expect(q.extras.STATION_CALLSIGN).toBe('K0CJH');
  });

  it('round-trips multi-line comments', () => {
    const text = buildAdif([{ call: 'W1AW', comment: 'first line\nsecond line' }]);
    const { qsos } = parseAdif(text);
    expect(qsos[0].comment).toBe('first line\nsecond line');
  });

  it('tolerates a null/empty qso list', () => {
    expect(parseAdif(buildAdif(null)).qsos).toEqual([]);
    expect(parseAdif(buildAdif([])).qsos).toEqual([]);
  });
});
